### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dudulasry** [Paubox/paubox-python#6]
Hi there,

I'm currently working on integrating Paubox into some service we have, in our company. During that integration, I encountered in the following error:

![image](https://user-images.githubusercontent.com/74605177/104124884-f7d51b80-535b-11eb-8130-0672cdfa320c.png)

I understand that the current version of python that this package uses is 2.7.  We, however, use Python 3.

Can you please consider migrating your code to Python 3?

**Comment by gbhojak** [comment]
We are running into same issue. This is quite critical to us.
Is there a way this can be expedited?

**Comment by dudulasry** [comment]
@gbhojak We managed to solve the problem. What we did, eventually, was to create our own wrapper class. That class knows how to send POST messages to the redox api.

**Comment by niwong** [comment]
Hey @gbhojak, @dudulasry,

The @Paubox engineering team released a separate Python 3 SDK for our Email API that can be found here: https://github.com/Paubox/paubox-python3. With that, I'll go ahead and close this issue 👍🏼
